name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Run ESLint
        run: npm ci
      - name: Rum Test
        run: npm test
      - name: Build
        run: npm run build

  code_quality:
    runs-on: ubuntu-latest
    requires: build
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run ESLint (same as build)
        with:
          node-version: '14'
        run: npm test

  docker_build:
    runs-on: ubuntu-latest
    requires: [build, code_quality]
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub (optional)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t gclub/rebel .
