name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
      - 'feat/**'
      - 'fix/**'
  pull_request:
    branches:
      - 'feature/**'
      - 'feat/**'
      - 'fix/**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Run ESLint
        run: npm ci
      - name: Rum Test
        run: npm test
      - name: Build
        run: npm run build

  code_quality:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run ESLint (same as build)
        run: npm ci

  docker_build:
    runs-on: ubuntu-latest
    needs: [build, code_quality]
    steps:
      - uses: actions/checkout@v3
      # - name: Login to Docker Hub (optional)
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t gclub/rebel .
